### ISSUE TITLE
rviz segmentation fault

### ISSUE THREAD

**Issue by vbschettino** [AndreGilerson/rviz_vive#2]
Hi,

Following the instructions on the readme I'm able to build the plugin, but whenever I try to add it to rviz the application crashes with a segmentation fault. Is there perhaps a step missing on the instructions?

**Comment by AndreGilerson** [comment]
Die you source the corresponding File? Before Starring Rviz you have to source either the devel/setup.sh or setup.zsh

**Comment by vbschettino** [comment]
Hi Andre,

Yes, I sourced setup.bash before starting roscore. Rviz runs correctly until the plugin is added.

**Comment by AndreGilerson** [comment]
You have to source the file in the terminal youre Starring Rviz in, Not the one with the roscore

**Comment by vbschettino** [comment]
Yes, of course, I'm sourcing it in all of them. As I said, rviz is running fine and I can visualize data from ros topics until the plugin is added, so I don't think sourcing is the problem. (This is just the default setup.bash file created by catkin, right?)

Would the crash logs following the segmentation fault help in any way?

[_opt_ros_kinetic_bin_rviz.1000.crash.txt](https://github.com/AndreGilerson/rviz_vive/files/2562147/_opt_ros_kinetic_bin_rviz.1000.crash.txt)
[_opt_ros_kinetic_lib_rviz_rviz.1000.crash.txt](https://github.com/AndreGilerson/rviz_vive/files/2562148/_opt_ros_kinetic_lib_rviz_rviz.1000.crash.txt)

**Comment by SergTrip** [comment]
Hi Andre,

I had the same problem. Did you try to use this manual?

https://github.com/ValveSoftware/SteamVR-for-Linux

After command 

~/.steam/steam/ubuntu12_32/steam-runtime/run.sh rosrun rviz rviz

it starts to work for me.

**Comment by AndreGilerson** [comment]
Ich remember having to use the steam run.sh as well, but I don't have to now. I'll investigate what I have changed

**Comment by SergTrip** [comment]
Sorry for the mistake, the comment was for vbschettino.

**Comment by vbschettino** [comment]
Hi,

Thanks SergTrip, that fixed it for me! I also follow that manual for other applications that need steamVR, but since there was a step on the readme saying to adapt the path to openvr I thought this wouldn't be needed, and honestly forgot to try it.

Thanks a lot for making this plugin available Andre, really cool! Should I close the issue or do you want to change something first?
